def now = new Date()
def versionTag = now.format("yyyyMMdd")
def image = "jdk17"

podTemplate(
  inheritFrom: 'composer-jenkins-persona-deploy',
  namespace: "project-30262",
  containers: [
    containerTemplate(name: 'jnlp', image: "634769451609.dkr.ecr.eu-west-1.amazonaws.com/jenkins-agents/inbound-agent:latest-RC", 
      envVars: [
        envVar( key: "JENKINS_URL", value: "http://composer-jenkins.composer-jenkins.svc.cluster.local:8080/jenkins")
      ],
      resourceLimitCpu: "500m",
      resourceRequestCpu: "500m",
      resourceRequestMemory: "1000Mi",
      resourceLimitMemory: "1000Mi"
    ),
    containerTemplate(
      name: 'kaniko',
      image: '634769451609.dkr.ecr.eu-west-1.amazonaws.com/jenkins-agents/kaniko:latest-RC', 
      envVars: [
        envVar( key: "http_proxy", value: "http://fwpprod.internal-devops-dxc-cegeka.be:3128"),
        envVar( key: "https_proxy", value: "http://fwpprod.internal-devops-dxc-cegeka.be:3128"),
        envVar( key: "no_proxy", value: "localhost,127.0.0.1,cluster.local,kubernetes.default")
      ],
      resourceLimitCpu: "2000m",
      resourceRequestCpu: "2000m",
      resourceRequestMemory: "4000Mi",
      resourceLimitMemory: "4000Mi",
      args: "9999999",
      command: "sleep"
    )
  ],
  volumes: [
    secretVolume(
      mountPath: "/kaniko/.docker",
      secretName: "project-30262-secret-persona-kaniko-config"
    )
  ]
  ) {
  node(POD_LABEL) {
    stage('Cloning Git') {
      container('jnlp') {
        //clean workspace
        //sh "rm -rf $WORKSPACE/*"
        checkout scm
        this.workspace = this.pwd();
        sh 'pwd'
        sh 'ls -lat'
      }
    }

    stage('kaniko - build and push image to registry') {
      container(name: 'kaniko', shell: '/bin/sh') {
        dir("containers/${image}") {
          sh 'ls -lat'
          sh 'rm -f /kaniko/Dockerfile'
          sh """#!/bin/sh
                CONTEXT=\$(pwd)/context
                mkdir -p /tmp/cache

                /kaniko/executor \
                    --dockerfile="Dockerfile" \
                    --cache="true" \
                    --cache-dir="/tmp/cache" \
                    --destination="composer-registry-30262-nexus-docker.composer-nexus.svc.cluster.local:6003/jenkins-images/${image}:${versionTag}" \
                    --context="dir://\$CONTEXT" \
                    --build-arg=PROXY="http://fwpprod.internal-devops-dxc-cegeka.be:3128"
                """
        }
            // --destination="composer-registry-30262-nexus-docker.composer-nexus.svc.cluster.local:6003/jenkins-agent:latest" \
      }
    }
  }
  
}

  
